# Site
title: "Resiliência: Residência Artística"

# URL
url: https://resilience.silo.org.br
baseurl: ''
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 6664
future: false

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"

# Data
social:
  facebook: ""
  instagram: "https://www.instagram.com/silo.arte.e.latitude.rural"
  github: ""
  twitter: "https://twitter.com/SiloLatitude"
  youtube: ""
  vimeo: ""
  soundcloud: ""
  tumblr: ""
  pinterest: ""
  envelope-o: "mailto:resilience.residence@silo.org.br"
twitter_user: "SiloLatitude"

# prose.io
prose:
  media: 'media/images'
  ignore:
    - .gitignore
    - _config.yml
    - _data
    - _includes
    - _layouts
    - _pages
    - _sass
    - css
    - js
    - CNAME
    - TODO.md
    - publish.sh
    - media/favicons
    - media/swipebox
    - media/images/logos
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Nome"
          placeholder: "Nome da Pessoa"
      - name: "cover"
        field:
          element: "text"
          label: "imagem de capa"
          placeholder: "media/images/cover.jpg"
      - name: "swipebox"
        field:
          element: "text"
          label: "prefixo dos arquivos de imagem para serem incluidos na galeria"
          placeholder: "p1_"
